<?php

class ListsEnums{
	
	public static 	$Wojewodztwo = 0,
    				$PrzyczynaRezygnacji = 1,	
    				$RodzajZadania = 2,
    				$PrzeznaczenieLokalu = 3,
    				$RodzajBudynkuLokal = 4,
				    $RodzajBudynkuMieszkanie = 5,
				    $ZrodloInformacji = 6,
				    $PodstawaNabycia = 7,
				    $Gaz = 8,
				    $Prad = 9,
				    				
				    $Kanalizacja = 10,
				    $Woda = 11,
				    $Otoczenie = 12,
				    $Dojazd = 13,
				    $Ogrzewanie = 14,
				    $Spoldzielnia = 15,
				    $TypKuchni = 16,
				    $RodzajKuchni = 17,
				    $TypLazienki = 19,
				
				    $Glazura = 20,
				    $WannaLazienki = 21,
				    $Taras = 24,
				    $Balkon = 25,
				    $TechnologiaBudowlana = 26,
				    $GarazMieszkanie = 27,
				    $Widok = 28,
				    $Pietro = 29,
				
				    $Okna = 30,
				    $Instalacje = 31,
				    $PolozenieLokalu = 32,
				    $WitrynaWystawowa = 33,
				    $Wejscie = 34,
				    $Podlogi = 35,
				    $PrzeznaczenieDzialki = 36,
				    $UksztaltowanieDzialki = 37,
				    $KsztaltDzialki = 38,
				    $RodzajDomu = 39,
				
				    $MaterialKonstrukcyjny = 40,
				    $PokrycieDachu = 41,
				    $StanBudynku = 42,
				    $Garaz = 43,
				    $OgrodzenieDzialki = 44,
				    $PolozenieHali = 45,
				    $PrzeznaczenieHali = 46,
				    $MaterialKonstrukcyjnyHali = 47,
				    $Oplaty = 48,
				    $WyposazeniePokoi = 49,
				
				    $WyposazenieLazienki = 50,
				    $WyposazenieKuchni = 51,
				    $WyposazeniePrzedpokoi = 52,
				    $Kategorie = 53,
				    $Rozklad = 56,
				    $Ochrona = 57,
				    $StanWybudowania = 58,
				    $OplatyLiczniki = 59,
				
				    $KomunikatyPocztyWewnetrznej = 60,
				    $Sciany = 67,
				    $WyposazenieWC = 68,
				    $ZrodloInformacjiPortale = 70,
				
				    $RodzajPomieszczenia = 106,
				    $StanPodlogi = 107,
				    $meblowanie = 108,
				    $TypElewacji = 109,
				
				    $StanPrawnyGruntu = 119,
				    $Usytuowanie = 120,
				
				    $WarunkiZabudowy = 132,
				    $Kraj = 133,
				    $Indeksacja = 134,
				    $Komunikacja = 135,
				    $TypPowierzchni = 136,
				    $PolozenieBiurowca = 137,
				    $SposobPrzyjecia = 138,
				    $StanLokalu = 139,
				
				    $PowodWycofania = 140,
				    $RodzajUmowyPrzedwstepnej = 141,
				    $KosztyZmianyStanuLokalu = 142,
				    $TerminWydania = 143,
				    $RodzajUmowyPoszukiwania = 144,
				    $RodzajKontaktuZKlientem = 145,
				
				    $DostepSamochodow = 150,
				    $RodzajDostepuDoHali = 151,
				    $DozorBudynku = 152,
				    $Glosnosc = 153,
				    $StanPrawnyLokal = 154,
				    $Ogloszenia = 155,
				    $MiejsceNaReklame = 156,
				    $StanBiurowca = 157,
				    $KosztyEksploatacyjne = 158,
				    $TypKaucji = 159,
				
				    $ZabudowaDzialki = 160,
				    $PotrzebyPsychologiczne = 161,
				    $TypySpoleczne = 162,
				    $FirmaGrupa = 163,
				    $KategoriaInwestycji = 164,
				    $Zobowiazania = 165,
				    $OpcjeDodatkowe = 166,
				
				    $RodzajKosztu = 170,
				    $KlasyfikacjaPoszukiwania = 171;		
	
}